version 2

jobs:
    build:
        docker:
            - image: python:3.7.3-stretch
        
        working_directory: :~/repo
        
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "requirements.txt" }}
                    - v1-dependencies
            - run:
                name: Install dependencies
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    make install
                    sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-linux-x86_64 && \
                    chmod +x /bin/hadolint
            - save_cache:
                paths:
                    - ./venv
                key: v1-dependencies-{{ checksum "requirements.txt" }}
            - run:
                name: Run Lint
                command: |
                    . venv/bin/activate
                    make lint